### ISSUE TITLE
Several translations issues

### ISSUE THREAD

**Issue by liushuyu** [AOSC-Dev/pug-zh-cn#1]
In `getting-started.md`: 
```
调用这个编译出来的函数，并且传入您的数据， 嘭！
```
The `Boom` here should mean `perfect` or `great`. I suggest to translate to `很好`.

**Comment by liushuyu** [comment]
In `migration-v2.md`:
```
让人非常古怪
```
Translated as `Make _people_ very wired`, yes, this translation is wired too. 
Just say `让人感到非常困惑`

**Comment by LionNatsu** [comment]
Good advice, thanks for reviewing!
